SysmelClassDefinition(ProtoObject);
    SysmelClassDefinition(Object);

SysmelClassDefinition(Type);
    SysmelClassDefinition(TypeUniverse);
    SysmelClassDefinition(NominalType);
    SysmelClassDefinition(Behavior);
        SysmelClassDefinition(Class);
        SysmelClassDefinition(Metaclass);

SysmelClassDefinition(Boolean);
    SysmelClassDefinition(True);
    SysmelClassDefinition(False);

SysmelClassDefinition(Magnitude);
    SysmelClassDefinition(Character);
    SysmelClassDefinition(Number);
        SysmelClassDefinition(Float);
            SysmelClassDefinition(BoxedFloat);
            SysmelClassDefinition(SmallFloat);
        SysmelClassDefinition(Integer);
            SysmelClassDefinition(SmallInteger);

SysmelClassDefinition(Collection);
    SysmelClassDefinition(SequenceableCollection);
    SysmelClassDefinition(ArrayedCollection);
        SysmelClassDefinition(String);
        SysmelClassDefinition(SymbolString);
